name: time_keeper
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  firebase_core: ^0.3.4
  firebase_analytics: ^2.1.1+3

  cloud_firestore: ^0.10.1

  firebase_auth: ^0.8.4+5

  provider: 3.1.0
  rxdart: ^0.21.0
  intl: ^0.16.1
  font_awesome_flutter: 8.4.0

  pull_to_refresh: ^1.5.8
  flutter_local_notifications: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true